Swap volumes for mounts
mantidproject/errorreports pull request #31
Opened 2022-01-24 16:30 UTC by DavidFair

This gives us a number of benefits
- Makes backing up the image trivial compared to docker vols
- Devs can easily delete / modify /inspect webdata
- docker-compose up "just works"

2022-01-25 13:19 UTC, martyngigg reviewed
Thanks for these changes. I agree that the volume mounts are far easier to deal with, it's also how Discourse work with their shared data too.

I assume we still need the boot script so it creates the network for nginx?

2022-01-25 14:40 UTC, martyngigg requested changes
I'm not sure why but if I try `docker-compose up` then I get an error in the `web` container:
```
web_1                 |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1                 |     return _bootstrap._gcd_import(name[level:], package, level)
web_1                 |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
web_1                 |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
web_1                 |   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
web_1                 | ModuleNotFoundError: No module named 'wsgi'
```
I've actually never understood why the web container exists. It just holds the built code but that could be in an image.

2022-01-25 15:53 UTC, DavidFair commented
This was because we're mounting an empty dir over the working dir

Me and Daniel have fixed this, we also bumped Django to 3.2 (the next LTS) as the current one is EOL this quarter and has already broken with newer `psycopg2-binary`

2022-01-26 09:28 UTC, DanielMurphy22 approved these changes
Works really well! It's great the css works again.

Not related to this PR but we don't seem to look at the users name on error reports on the django server. No real problem because it possible to check on adminer!
![Screenshot 2022-01-26 at 09 23 15](https://user-images.githubusercontent.com/55980573/151137515-7cf9b9f2-593c-4624-99cf-9619a4ac80bc.png)

2022-01-26 11:41 UTC, DavidFair commented
> Works really well! It's great the css works again.
> 
> Not related to this PR but we don't seem to look at the users name on error reports on the django server. No real problem because it possible to check on adminer! ![Screenshot 2022-01-26 at 09 23 15](https://user-images.githubusercontent.com/55980573/151137515-7cf9b9f2-593c-4624-99cf-9619a4ac80bc.png)

Can you open an issue?
All we need to do is add that field to the list of displayed fields in Django when we next look at it

2022-01-26 13:13 UTC, martyngigg commented
> > With a straight `docker-compose` up I'm getting:
> > `` ERROR: Network nginx_net declared as external, but could not be found. Please create the network manually using `docker network create nginx_net` and try again. ``
> 
> This is expected, the host network is called `nginx_net`. The boot script now simply creates that external network for us mirroring our config on production

Thanks. I understand now, the straight `docker-compose up` will now just work assuming the `nginx_net` network is created so they can automatically be brought up?

2022-01-26 13:30 UTC, martyngigg commented on docker-compose.yml
>      image: postgres:latest
This is more of a note/question and I won't hold this up as it hasn't changed. I thought I would try to setup a local copy of the db so I rsync'd the `pgdata` directory from linode to my machine. When I try to start the server the postgres container won't start as it says there is a mismatch between the version of postgres running and the data that is in the directory.

Should we be pinning the major version and not using latest for reproducibility?

2022-01-26 13:30 UTC, martyngigg approved these changes
Confirmed this works for me too.

I've got one question but it's not about the changes here.

2022-01-26 13:30 UTC, merged