GitHub issue handler
mantidproject/errorreports pull request #56
Opened 2024-04-26 10:29 UTC by jhaigh0

This is the main pr for "automatic github issue creation" of the Mantid error reporter improvements Epic.

What's been added:

- A new database model `GithubIssue` comprised of a repo address and an issue number
- `github_issue_manager.py` which contains the main funcion `get_or_create_github_issue` which does the following
  - Searches the database for a githubIssue with a matching repo and stacktrace (the stacktrace is compared irrespective of the install location / any local informaiton)
    - If one is found, a comment containing the report info is added to that issue
    - If no issue is found, then a new one is made

Two new environment variables have been added
 - `GIT_AUTH_TOKEN` is the auth token of the account used to create the github issues / comments (on the live version of the error reports site this will be an auth token from https://github.com/Mantid-Error-Reporter)
 - `GIT_ISSUE_REPO` the repository to create the issues in (e.g `'ISISNeutronMuon/mantid-isis-support'`)

I've also changed the slack message poster so that, id an issue is created / found, it'll be linked in the slack message.

2024-05-07 14:12 UTC, robertapplin requested changes

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/test_trim_stacktrace.py
> +        pass
Is this meant to be here?

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/github_issue_manager.py
> +comment_text_template = Template("""
Same for these constant variables in caps?

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/github_issue_manager.py
> +def _search_for_repeat_user(uid: str, github_issue: GithubIssue) -> bool:
Can this function using the python `any()` function?

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/github_issue_manager.py
> +    Returns a rimmed and os non-specific version of the stacktrace given
```suggestion
    Returns a trimmed and os non-specific version of the stacktrace given
```

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/github_issue_manager.py
> +**Additionl Information**
```suggestion
**Additional Information**
```

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/github_issue_manager.py
> +**Additionl Information**
```suggestion
**Additional Information**
```

2024-05-07 14:12 UTC, robertapplin commented on web/services/github_issue_manager/github_issue_manager.py
> +        report: The report recived by ErrorViewSet
```suggestion
        report: The report recieved by ErrorViewSet
```

2024-06-04 10:35 UTC, thomashampson requested changes
I think I found a couple of cases that the stack trace trimming would miss, which could result in new issues being created rather than comments added to existing issues.

2024-06-04 10:35 UTC, thomashampson commented on web/services/github_issue_manager/test_search_for_matching_stacktrace.py
> +    entries = [
I think the following would not be matched by the regex:

`  File "/opt/mantidworkbench6.9/lib/python3.10/site-packages/mantid/simpleapi.py", line 1083, in __call__`

and also the following kind of thing that I found in the error reports slack channel:

```
Exception: MDWorkspace::getExperimentInfo(): expInfoIndex is out of range.
  at line 152 in '/usr/local/anaconda/envs/mantid-dev/plugins/python/algorithms/ConvertWANDSCDtoQ.py'
```

2024-06-04 10:35 UTC, thomashampson commented on web/services/github_issue_manager/test_trim_stacktrace.py
> +        examples = {
you might want to add the above examples to this test too

2024-06-13 15:33 UTC, thomashampson approved these changes
Let's get this in and get it working

2024-06-13 15:33 UTC, merged